"""
director.py - 'Movie Making' workflow (v1).

Pipeline per scene:
  1. Send the scene's reference images (character sheet, face close-up, scene
     image(s)) plus the scene summary to the local LLM (tools/ai_call.py),
     which is driven by the FL2VA prompt-writer system prompt in
     director_system_prompt.md, and get back a structured MiniMax H3 FL2VA
     prompt (alignment line / summary / subject_definitions /
     integrated_multimodal_description / soundscape / music).
  2. Build a MiniMax H3 reference-to-video request (tools/iv2v_h3.py) from that
     prompt + the reference images and execute it on ComfyUI.
  3. Save the resulting clip, then describe its ending state with a separate
     vision AI call (the FL2VA contract is text-only for videos) and request
     a Mode A continuation prompt; the next clip is generated with the
     previous clip as the motion/continuation reference passed to iv2v.
  4. Repeat for the configured number of clips, then move to the next scene.

Every scene is a self-contained dict so future versions can supply entirely
new image sets per scene without changing the control flow:

    SCENES = {
        "scene_01": {
            "summary": "text of what happens in the scene",
            "img_1": {"path": "path/to/charsheet.png",
                      "description": "subject sheet, three views of the woman"},
            "img_2": {"path": "path/to/closeup.png",
                      "description": "close-up of the same woman's face"},
            "img_3": {"path": "path/to/kitchen.png",
                      "description": "empty kitchen plate, morning light"},
            # optional: a scene that opens mid-action as a continuation
            # "path" may be a direct file path OR the id of another scene
            # (resolved at runtime to that scene's FIRST generated clip,
            # clip_1, as recorded in generated_videos).
            # Referenced scenes must run BEFORE this scene in the same run;
            # an unresolvable "path" raises an error rather than guessing.
            "video": {"path": "scene_01",   # or "path/to/prev_clip.mp4"
                      "description": None},   # None -> auto-generated by AI
            "clips": 2,          # optional override of clips_per_scene
            "duration": 10.0,     # optional per-scene seconds per clip
        },
        ...
    }

img_N keys are attached to the LLM in numeric order (img 1 = first attached
image) exactly as the FL2VA prompt writer expects; each image's "description"
becomes its note in the <inputs> manifest. A scene's "video" entry makes its
first clip a Mode A continuation of that video; the ending-state description
is generated at runtime by a separate AI call that watches the video (see
MovieDirector.describe_video_end) unless one is supplied. iv2v_h3 supports a
maximum of 4 reference images per clip; extra img_N entries are truncated
with a warning.

Scene chaining: by default (chain_scenes=False) a scene without its own
"video" entry opens cold — its first clip is a fresh images+summary
generation. With chain_scenes=True such a scene instead continues from the
previous scene's last generated clip (Mode A), reusing the ending-state
description already produced for that clip. An explicit "video" entry
always takes precedence over chaining.

One random seed is drawn per scene and reused for all of its clips; it is
recorded in the manifest for reproducibility.

Output layout (under output_dir):
    <scene_id>/<scene_id>_clip01.mp4 ...            generated clips
    <scene_id>/<scene_id>_clip01_final_frame.png    each clip's final frame
                                                    (SaveImage node 209), used
                                                    for the ending-state vision
                                                    call instead of re-sampling
                                                    the video
    <scene_id>/<scene_id>_clip01_input.json         exact inputs per clip: the
                                                    brief and system prompt sent
                                                    to the prompt-writer AI, the
                                                    assets, and the returned
                                                    FL2VA prompt
    movie_manifest.json                             every clip with its prompt,
                                                    ref images, seed,
                                                    continuation source, final
                                                    frame, and ending
                                                    description; rewritten after
                                                    every clip so a crashed run
                                                    stays inspectable
"""

import json
import os
import random
import re
import subprocess
import sys
import tempfile
from datetime import datetime

# Make sibling packages importable when run as a script
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(CURRENT_DIR)

from tools.ai_call import AICall
from tools.iv2v_h3 import iv2v
from call_comfyui import ComfyUIlocal, WORKFLOWS

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
WORKFLOWS["iv2v_h3"] = os.path.join(CURRENT_DIR, "comfy_workflows", "minimax_h3_flex_cinematic.json")

MAX_REF_IMAGES = 4  # hard limit imposed by the MiniMax H3 R2V node

# FL2VA prompt-writer system prompt (see that file for the full input/output
# contract: numbered images, <inputs> manifest, Mode A/B/C alignment, etc.)
SYSTEM_PROMPT_PATH = os.path.join(CURRENT_DIR, "director_system_prompt.md")


def load_system_prompt(path=SYSTEM_PROMPT_PATH):
    """Load the FL2VA prompt-writer system prompt from disk."""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# System prompt for the separate vision call that describes a clip's ending
# state (used as the text description of <Video 1> in continuation briefs).
VIDEO_DESCRIPTION_SYSTEM = """You are a video analyst for a film director.

You receive the FINAL 2 seconds of a clip as frames at 4fps. The last image is the true final frame of the clip. Describe how the clip ends, anchored on that last frame. Use the earlier frames ONLY to identify motion that is still in progress (mid-turn, mid-step, hand lowering, settling to stillness).

Write 3-6 sentences, in this order:
1. PEOPLE — each person's position in the room and in the frame (left/right/center, near/far), pose, and facing direction on the last frame.
2. MOTION — what movement is in progress or just completing as the clip ends. If a subject has come to rest, say so and say what they settled from.
3. CAMERA — framing size (close-up/medium/wide), height and angle, and any camera movement in progress (static, handheld sway, pan, push-in, drift) with its direction.
4. LIGHTING — quality (hard/soft), direction, and color of the visible light sources.
5. SET/PROPS — the key visible set elements and prop states (held objects, open/closed doors, items on surfaces).

Rules:
- Concrete and spatial only. Name screen positions (frame left/right/center, foreground/background).
- Describe expressions only as visible facial states, not inner feelings.
- No preamble, no headings, no bullet points — flowing sentences.
- Do not guess what happens after the last frame.
- Do not describe anything not visible in the frames.

EXAMPLE_USER_TEXT = "Describe what happens in the video: position of the characters, action in progress at the final frames, camera framing and movement, and lighting."

EXAMPLE_ASSISTANT = A single woman fills the left-center of the frame from the chest up, near the camera, her torso angled slightly toward frame right and her head turned to face the lens directly; she holds a black-lidded glass coffee carafe in both hands at chest height near the bottom-center of frame. Over the final second she has just withdrawn her right hand from a reach toward the lens, and her open laugh is subsiding into a broad closed-mouth smile as her shoulders drop — she is nearly still on the last frame. The camera is a handheld medium close-up at eye level, with a subtle rightward drift that brings a little more of the upper cabinets into frame right by the final frame. Lighting is a mix of warm amber under-cabinet strip light glowing across the marble backsplash behind her and softer, cooler daylight from off-frame left that models her face and catches the stainless range hood in the upper-left corner. The set shows closed light-oak cabinet doors with brass pulls across the top of frame, a brass faucet behind her right shoulder, and a black espresso machine on the counter at frame right.
"""


# ---------------------------------------------------------------------------
# ffmpeg helpers
# ---------------------------------------------------------------------------
def _probe_duration(video_path):
    """Return the video duration in seconds via ffprobe, or None on failure."""
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", video_path],
            capture_output=True, text=True, check=True)
        return float(result.stdout.strip())
    except Exception as e:
        print(f"Warning: ffprobe could not read duration of {video_path} ({e})")
        return None


def _extract_last_frame(video_path):
    """Extract the exact final frame of a clip as a PNG via ffmpeg.

    Fallback for when the workflow did not produce a final-frame image
    (e.g. the SaveImage node is missing). Returns the temp-file path, or
    None on failure (caller falls back to the video tail).
    """
    fd, out_path = tempfile.mkstemp(prefix="director_lastframe_", suffix=".png")
    os.close(fd)

    cmd = [
        "ffmpeg", "-y",
        "-sseof", "-0.1",          # seek to just before the end (input seek)
        "-i", video_path,
        "-frames:v", "1",
        "-q:v", "2",
        out_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 or not os.path.isfile(out_path) or os.path.getsize(out_path) == 0:
        print(f"Warning: ffmpeg last-frame extraction failed for {video_path}: {result.stderr[-500:]}")
        try:
            os.remove(out_path)
        except OSError:
            pass
        return None
    return out_path


def _trim_video_tail(video_path, tail_seconds=2.0):
    """Trim a clip to just its final `tail_seconds` (re-encoded, audio kept).

    The vision call only needs the ending state, so sending the whole clip
    wastes bandwidth and context. -ss is placed before -i for fast input
    seeking; since we re-encode, the cut is still frame-accurate.

    Returns the trimmed temp-file path, or None if the trim failed (caller
    should fall back to the full video).
    """
    duration = _probe_duration(video_path)
    if duration is None:
        return None

    start_time = max(0.0, duration - tail_seconds)
    clip_duration = duration - start_time
    if clip_duration <= 0:
        return None

    # No point re-encoding if the clip is already ~the tail length.
    if start_time <= 0.0:
        return video_path

    fd, out_path = tempfile.mkstemp(
        prefix="director_tail_", suffix=os.path.splitext(video_path)[1] or ".mp4")
    os.close(fd)

    cmd = [
        "ffmpeg", "-y",
        "-ss", f"{start_time:.6f}",
        "-i", video_path,
        "-t", f"{clip_duration:.6f}",
        "-map", "0:v:0",
        "-map", "0:a?",          # keep audio if the clip has any
        "-c:v", "libx264",
        "-preset", "veryfast",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-ar", "44100",
        "-ac", "2",
        "-movflags", "+faststart",
        out_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 or not os.path.isfile(out_path):
        print(f"Warning: ffmpeg tail trim failed for {video_path}: {result.stderr[-500:]}")
        try:
            os.remove(out_path)
        except OSError:
            pass
        return None
    return out_path


# ---------------------------------------------------------------------------
# Director
# ---------------------------------------------------------------------------
class MovieDirector:
    """Orchestrates LLM prompt-writing + iv2v clip generation across scenes."""

    def __init__(self,
                 scenes,
                 output_dir="movie_output",
                 clips_per_scene=2,
                 clip_duration=10.0,
                 megapixels=0.6,
                 aspect_ratio="16:9 (Widescreen)",
                 chain_scenes=False,
                 ai_client=None,
                 comfy_client=None,
                 turbo_lora=True,
                 quant="int8",
                 ai_timeout=900):
        """
        Args:
            scenes: dict of scene configs (see module docstring). Insertion
                    order defines shooting order.
            output_dir: root directory for clips + manifest.
            clips_per_scene: default number of clips per scene (each scene can
                             override with its own "clips" value).
            clip_duration: default seconds per clip (scene may override).
            megapixels / aspect_ratio: passed through to the iv2v workflow.
            chain_scenes: when True, a scene without its own "video" entry
                          continues from the previous scene's last clip
                          (Mode A). Default False — scenes open cold unless
                          they declare a "video" entry.
            ai_client / comfy_client: optional pre-built clients (for testing).
        """
        self.scenes = scenes
        self.output_dir = output_dir
        self.clips_per_scene = clips_per_scene
        self.clip_duration = clip_duration
        self.megapixels = megapixels
        self.aspect_ratio = aspect_ratio
        self.chain_scenes = chain_scenes
        self.turbo_lora = turbo_lora
        self.quant = quant

        # Reasoning models need a big budget: their hidden reasoning tokens
        # count against max_tokens, and FL2VA prompts themselves are long.
        # Timeout must also cover slow prompt processing (large base64 images
        # on a 12B model), not just generation.
        self.ai = ai_client or AICall(max_tokens=18192, timeout=ai_timeout)
        self.comfy = comfy_client or ComfyUIlocal()
        self.system_prompt = load_system_prompt()

        os.makedirs(self.output_dir, exist_ok=True)

        # Registry of every clip generated this run, keyed by scene id and
        # then a simple per-scene counter key:
        #     {scene_id: {"clip_1": path, "clip_2": path, ...}}
        # A scene's "video" entry may name a previous scene instead of a file
        # path (clip paths are created dynamically at runtime), in which case
        # it resolves to that scene's first generated clip (clip_1).
        self.generated_videos = {}

        # Manifest records everything we generate (useful for resume/debug)
        self.manifest_path = os.path.join(self.output_dir, "movie_manifest.json")
        self.manifest = {"scenes": {}, "created": datetime.now().isoformat()}

    # ------------------------------------------------------------------
    # Scene asset extraction + video description
    # ------------------------------------------------------------------
    @staticmethod
    def _scene_images(scene_cfg):
        """Extract ordered image entries from a scene config.

        Returns a list of {"key", "path", "description"} dicts sorted by the
        numeric suffix of the img_N keys (img_1, img_2, ...), truncated to
        MAX_REF_IMAGES.
        """
        entries = []
        for key, value in scene_cfg.items():
            match = re.fullmatch(r"img_(\d+)", key)
            if match and isinstance(value, dict) and value.get("path"):
                entries.append({
                    "num": int(match.group(1)),
                    "path": value["path"],
                    "description": value.get("description") or os.path.basename(value["path"]),
                })
        entries.sort(key=lambda e: e["num"])

        if len(entries) > MAX_REF_IMAGES:
            print(f"Warning: scene supplies {len(entries)} images, "
                  f"truncating to {MAX_REF_IMAGES}.")
            entries = entries[:MAX_REF_IMAGES]
        if not entries:
            raise ValueError("Scene config must contain at least one img_N entry.")
        return entries

    def describe_video_end(self, video_path, fallback_text=None, final_frame_path=None):
        """
        Ask the vision LLM to describe a clip's ending state.

        When `final_frame_path` is given (the SaveImage output saved next to
        the clip), the true final frame is sent directly as an image — no
        ffmpeg trim and no video upload needed. Without it, the frame is
        extracted from the clip with ffmpeg, and if that fails the final few
        seconds are sent as a trimmed video (AICall samples frames at 4 fps,
        last frame always included). On failure falls back to
        `fallback_text` so a long run isn't killed after a clip was already
        generated.
        """
        temp_files = []
        chat_kwargs = {}
        if final_frame_path and os.path.isfile(final_frame_path):
            chat_kwargs["images"] = [final_frame_path]
        else:
            extracted = _extract_last_frame(video_path)
            if extracted:
                temp_files.append(extracted)
                chat_kwargs["images"] = [extracted]
            else:
                trimmed = _trim_video_tail(video_path, tail_seconds=2.0)
                if trimmed and trimmed != video_path:
                    temp_files.append(trimmed)
                chat_kwargs["video"] = trimmed or video_path
        try:
            desc = self.ai.chat(
                prompt=("Describe what happens in the video: position "
                        "of the characters, action in progress at the final frames, "
                        "camera framing and movement, and lighting."),
                system_prompt=VIDEO_DESCRIPTION_SYSTEM,
                **chat_kwargs,
            )
            desc = desc.strip()
            if desc:
                print(f"\nEnding description for {os.path.basename(video_path)}:\n{desc}\n")
                return desc
        except Exception as e:
            print(f"Warning: video description call failed for {video_path} ({e})")
        finally:
            # Clean up temp files (never the original clip or the saved
            # final-frame image next to it).
            for temp_path in temp_files:
                try:
                    os.remove(temp_path)
                except OSError:
                    pass
        return fallback_text or "The prior clip ends; resume from its final frame."

    def _resolve_video_path(self, video_entry):
        """Resolve a scene's "video" entry to a real clip path.

        The entry's "path" may be:
          - a direct file path to a video file, or
          - the id of another scene, in which case the last clip generated
            for that scene (earlier in this run) is used. Scenes are not
            chained strictly sequentially — any earlier scene can be
            referenced, but it must have run before this one.

        Returns the resolved path, or None if it can't be resolved. Which will cause generation to happen still, just no video reference
        """
        path = video_entry.get("path")
        if not path:
            return None
        if os.path.isfile(path):
            return path
        # A scene id: use that scene's first clip generated this run. A scene
        # can produce several clips, so the reference must pick one — clip_1
        # is the deterministic default.
        scene_clips = self.generated_videos.get(path)
        if scene_clips:
            resolved = scene_clips.get("clip_1")
            if resolved:
                print(f"Resolved video entry '{path}' -> {resolved} (clip_1)")
                return resolved

        print(f"Warning: could not resolve video path '{path}' "
              f"(not a file, and no clips generated this run for a scene with that id).")
        return None

    # ------------------------------------------------------------------
    # User brief builders (FL2VA input contract)
    # ------------------------------------------------------------------
    def _inputs_manifest(self, image_entries, previous_video_desc=None):
        """Number the attached images in order and give their descriptions.

        img numbering follows attachment order, exactly as the FL2VA system
        prompt expects (img 1 = first attached image). A prior video is
        declared as vid 1 and described in text only.
        """
        lines = []
        if previous_video_desc:
            lines.append(f"vid 1 the prior clip — {previous_video_desc}")
        for i, entry in enumerate(image_entries, start=1):
            lines.append(f"img {i} {entry['description']}")
        return "\n".join(lines)

    def _build_brief(self, summary, image_entries, duration, previous_video_desc=None):
        """Assemble the full user brief for the FL2VA prompt writer."""
        return (
            f"{summary}\n\n"
            f"Target clip duration: {duration:.2f} seconds.\n\n"
            f"<inputs>\n{self._inputs_manifest(image_entries, previous_video_desc)}"
        )

    # ------------------------------------------------------------------
    # Scene-input tracking
    # ------------------------------------------------------------------
    def _save_scene_input(self, scene_dir, clip_name, *, scene_id, summary,
                          duration, image_entries, brief, prompt,
                          previous_video=None, previous_video_desc=None):
        """Save the exact inputs sent to the scene-builder AI as JSON.

        One ``{clip_name}_input.json`` file per clip, written next to the
        clips in the scene folder so every generated video can be traced
        back to the brief, system prompt, and assets that produced it.

        Returns the path of the saved JSON file.
        """
        data = {
            "scene_id": scene_id,
            "clip_name": clip_name,
            "created": datetime.now().isoformat(),
            "mode": "continuation" if previous_video else "first_clip",
            "summary": summary,
            "duration": duration,
            "images": [{"img": i, "path": e["path"], "description": e["description"]}
                       for i, e in enumerate(image_entries, start=1)],
            "previous_video": previous_video,
            "previous_video_description": previous_video_desc,
            "system_prompt_path": SYSTEM_PROMPT_PATH,
            "system_prompt": self.system_prompt,
            "brief": brief,        # exact user message sent to the AI
            "fl2va_prompt": prompt,  # the AI's response (for convenience)
        }
        path = os.path.join(scene_dir, f"{clip_name}_input.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        return path

    # ------------------------------------------------------------------
    # LLM prompt generation
    # ------------------------------------------------------------------
    def write_scene_prompt(self, summary, image_entries, duration=None):
        """First clip of a scene: images + summary -> FL2VA prompt.

        Returns (fl2va_prompt, brief) — brief is the exact user message
        sent to the prompt-writer AI (tracked for reproducibility).
        """
        brief = self._build_brief(summary, image_entries, duration or self.clip_duration)
        prompt = self.ai.chat(
            prompt=brief,
            system_prompt=self.system_prompt,
            images=[e["path"] for e in image_entries],
        ).strip()
        if not prompt:
            raise RuntimeError("LLM returned an empty FL2VA prompt for a scene's first clip.")
        return prompt, brief

    def write_continuation_prompt(self, summary, image_entries, video_description,
                                  duration=None):
        """Continuation clip: prior clip's ending described in text -> FL2VA prompt.

        `video_description` comes from describe_video_end() (or the scene's
        explicit video entry) — the video itself is never sent to the LLM,
        only to iv2v as the motion reference.

        Returns (fl2va_prompt, brief) — brief is the exact user message
        sent to the prompt-writer AI (tracked for reproducibility).
        """
        brief = self._build_brief(
            summary,
            image_entries,
            duration or self.clip_duration,
            previous_video_desc=video_description,
        )
        prompt = self.ai.chat(
            prompt=brief,
            system_prompt=self.system_prompt,
            images=[e["path"] for e in image_entries],
        ).strip()
        if not prompt:
            raise RuntimeError("LLM returned an empty FL2VA prompt for a continuation clip.")
        return prompt, brief

    # ------------------------------------------------------------------
    # Clip generation
    # ------------------------------------------------------------------
    def generate_clip(self, prompt, ref_images, save_directory, file_name,
                      video_path=None, duration=None, seed=None):
        """Build the iv2v request and execute it on ComfyUI.

        Returns (clip_path, final_frame_path) on success — the final frame
        is the SaveImage node output saved next to the clip (or None if the
        workflow didn't produce one). Returns (None, None) on failure.
        """
        request = iv2v(
            prompt=prompt,
            image_path_list=ref_images,
            iv2v_workflow_path=WORKFLOWS["iv2v_h3"],
            save_directory=save_directory,
            video_path=video_path,
            duration=duration or self.clip_duration,
            megapixels=self.megapixels,
            aspect_ratio=self.aspect_ratio,
            turboLora=self.turbo_lora,
            quant=self.quant,
            seed=seed,
            file_name=file_name,
        )
        if "error" in request:
            print(f"iv2v request error: {request['error']}")
            return None, None

        # The clip and the final-frame image are saved side by side in the
        # scene folder (the audio file is downloaded but not persisted).
        output_paths = {request["node_id"]: os.path.join(request["save_path"], request["file_name"])}
        image_node = request.get("image_node_id")
        frame_name = request["file_prefix"].get(image_node) if image_node else None
        if image_node and frame_name:
            output_paths[image_node] = os.path.join(request["save_path"], frame_name)

        result = self.comfy.generate(
            workflow=request["workflow"],
            service_type=request["service_type"],
            input_files=request["input_files"],
            file_prefix=request["file_prefix"],
            output_paths=output_paths,
        )

        if not result.get("files"):
            print(f"Clip generation failed: {result.get('error', 'unknown error')}")
            return None, None

        # files[0] is often the audio output (its node isn't in output_paths,
        # so its saved_path is None) — take the entries that were saved.
        # The video clip is the only video output; the final frame is the
        # only image output (the audio entry's saved_path is None).
        saved = next((f.get("saved_path") for f in result["files"]
                      if f.get("saved_path") and f.get("mime_type", "").startswith("video/")), None)
        frame = next((f.get("saved_path") for f in result["files"]
                      if f.get("saved_path") and f.get("mime_type", "").startswith("image/")), None)
        print(f"Clip saved: {saved}")
        if frame:
            print(f"Final frame saved: {frame}")
        return saved, frame

    # ------------------------------------------------------------------
    # Scene / movie control flow
    # ------------------------------------------------------------------
    def run_scene(self, scene_id, scene_cfg, inherited_video=None):
        """Generate every clip for one scene.

        Args:
            inherited_video: optional (video_path, description) tuple carried
                over from the previous scene's last clip. Only used when the
                scene has no explicit "video" entry of its own.

        Returns:
            (clips, last_video) — clips is the list of saved clip paths;
            last_video is a (path, description) tuple of the final clip for
            chaining into the next scene, or None if nothing was generated.
        """
        summary = scene_cfg["summary"]
        n_clips = scene_cfg.get("clips", self.clips_per_scene)
        duration = scene_cfg.get("duration", self.clip_duration)

        scene_dir = os.path.join(self.output_dir, scene_id)
        os.makedirs(scene_dir, exist_ok=True)

        image_entries = self._scene_images(scene_cfg)
        ref_images = [e["path"] for e in image_entries]

        # Starting video: the scene's explicit "video" entry wins over an
        # inherited clip from the previous scene. The entry's "path" may name
        # a previous scene (resolved to that scene's last generated clip) or
        # be a direct file path.
        video_entry = scene_cfg.get("video")
        entry_video = None
        if isinstance(video_entry, dict):
            entry_video = self._resolve_video_path(video_entry)
            # A "video" entry was declared but couldn't be resolved — fail
            # loudly rather than silently opening the scene cold.
            if not entry_video and video_entry.get("path"):
                raise ValueError(
                    f"Scene '{scene_id}' declares a 'video' entry with path "
                    f"'{video_entry.get('path')}', but it could not be resolved "
                    f"(not a file, and no clips generated this run for that scene id). "
                    f"Make sure the referenced scene runs before this one.")

        if entry_video:
            previous_video = entry_video
            # Describe the prior clip's ending state up front, before any
            # FL2VA prompt is requested — the contract is text-only for
            # videos, so the prompt writer needs this description.
            previous_video_desc = (video_entry.get("description")
                                   or self.describe_video_end(previous_video))
        elif inherited_video:
            previous_video, previous_video_desc = inherited_video
        else:
            previous_video, previous_video_desc = None, None

        # Resolved starting point for the scene: every clip opens from here,
        # and it is recorded in each clip's manifest entry.
        start_video = previous_video
        start_video_desc = previous_video_desc

        clips = []
        for clip_idx in range(n_clips):
            clip_name = f"{scene_id}_clip{clip_idx + 1:02d}"
            print(f"\n{'=' * 70}\n{scene_id} — clip {clip_idx + 1}/{n_clips}\n{'=' * 70}")

            # Each clip draws its own seed. The first clip's seed is kept and
            # reused if a later clip's generation fails and is retried, so a
            # retry reproduces the same attempt instead of rerolling.
            seed = random.randint(1, 1000000000)
            if clip_idx == 0:
                loop_seed = seed

            # Every clip in the scene is its own take opening from the
            # scene's declared starting point — clips do NOT chain into each
            # other within a scene. Reset to the scene start each iteration.
            previous_video = start_video
            if start_video is not None:
                if clip_idx == 0:
                    # The first clip already has the ending-state description
                    # from the scene setup above; don't pay for it twice.
                    previous_video_desc = start_video_desc
                else:
                    previous_video_desc = self.describe_video_end(
                        start_video, fallback_text=start_video_desc)

            # 1. Get the FL2VA prompt from the LLM
            if previous_video is None:
                prompt, brief = self.write_scene_prompt(summary, image_entries, duration=duration)
            else:
                prompt, brief = self.write_continuation_prompt(
                    summary, image_entries, previous_video_desc, duration=duration)
            print(f"\nLLM prompt for {clip_name}:\n{prompt}\n")

            # 1b. Track the exact scene-builder inputs next to the clips
            input_json = self._save_scene_input(
                scene_dir, clip_name,
                scene_id=scene_id,
                summary=summary,
                duration=duration,
                image_entries=image_entries,
                brief=brief,
                prompt=prompt,
                previous_video=previous_video,
                previous_video_desc=previous_video_desc if previous_video else None,
            )

            # 2. Generate the clip (previous clip becomes the motion reference)
            saved, final_frame = self.generate_clip(
                prompt=prompt,
                ref_images=ref_images,
                save_directory=scene_dir,
                file_name=clip_name,
                video_path=previous_video,
                duration=duration,
                seed=seed
            )
            if saved is None:
                print(f"Stopping scene {scene_id} after clip {clip_idx} failed.")
                break

            clips.append(saved)
            # 3. Record this clip in the registry right away so downstream
            #    scenes can reference it by scene id (they get clip_1).
            clip_key = f"clip_{len(clips)}"
            self.generated_videos.setdefault(scene_id, {})[clip_key] = saved

            # 4. Describe the new clip's ending state. It does not feed the
            #    next clip (every clip opens from the scene start) — it is
            #    recorded for the manifest and becomes this scene's chaining
            #    hand-off via the last successful clip. The saved final frame
            #    is sent to the vision call when the workflow produced one.
            previous_video_desc = self.describe_video_end(saved, final_frame_path=final_frame)

            # 5. Record in the manifest after every clip (crash-safe)
            self.manifest["scenes"].setdefault(scene_id, []).append({
                "clip": saved,
                "final_frame": final_frame,
                "clip_key": clip_key,
                "clip_index": clip_idx + 1,
                "input_json": input_json,
                "prompt": prompt,
                "ref_images": ref_images,
                # Clips don't chain within a scene: every clip opens from the
                # scene's declared starting video (or cold).
                "continued_from": start_video,
                "video_description": previous_video_desc,
                "seed": seed,
                "turboLora": self.turbo_lora,
                "quant": self.quant,
            })
            self._save_manifest()

        # chain_scenes hand-off: the scene's last generated clip plus its
        # ending description, for the next scene to open from.
        last_video = (clips[-1], previous_video_desc) if clips else None
        return clips, last_video

    def run(self):
        """Run the full movie: every scene in dict order."""
        print(f"\nStarting movie run: {len(self.scenes)} scene(s) -> {self.output_dir}")
        carry = None  # (video_path, description) from the previous scene's last clip
        for scene_id, scene_cfg in self.scenes.items():
            inherited = carry if self.chain_scenes else None
            _, carry = self.run_scene(scene_id, scene_cfg, inherited_video=inherited)
        print(f"\nMovie run complete. Manifest: {self.manifest_path}")
        return self.manifest

    def _save_manifest(self):
        with open(self.manifest_path, "w") as f:
            json.dump(self.manifest, f, indent=2)


# ---------------------------------------------------------------------------
# Example / test entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    BASE = r"C:\Users\jared\Documents\code\haughtstudio\automation\luxuryAptEncounter"

    CHARACTER_FOLDER = "maya"

    SHEET = {"path": os.path.join(BASE, CHARACTER_FOLDER, "nsfw_char_sheet_1.png"),
             "description": "subject sheet, front three-quarter and full-body views of the woman"}
    SHEET_NSFW = {"path": os.path.join(BASE, CHARACTER_FOLDER, "nsfw_char_sheet.png"),
                 "description": "subject sheet, front three-quarter and full-body views of the woman"}
    CLOSEUP = {"path": os.path.join(BASE, CHARACTER_FOLDER, "close_up.png"),
               "description": "close-up of the same woman's face"}
    
    comfy_client = ComfyUIlocal()
    # Free VRAM before running
    comfy_client.aggressive_cleanup()


    director = MovieDirector(
        scenes={
            "scene_01_kitchen": {
                "summary": "The character makes coffee in the kitchen, humming to "
                           "herself in the distance, camera pushes towards her quickly then gets startled she notices the someone watching, and smiles and laughs flirtatiously, saying in a soft British accent 'Oh, you scared me!', then she swings her hand at the camera in a playful way and says 'don't do that!'",
                "img_1": SHEET,
                "img_2": CLOSEUP,
                "img_3": {"path": os.path.join(BASE, "apt_kitchen.png"),
                          "description": "empty modern apartment kitchen, morning light"},
                #"clips": 4,
            },
            "scene_02_livingroom": {
                "summary": "She walks into the living room, sits on the couch, and "
                           "in a soft British accent says 'do you want to feel my tits' she is looking directly at camera. a hand reaches forward from edge of frame, only their hand and arm are visible. they grab and fondle her left breast squeeze breast flesh deforms slightly, she moans when they do and smiles looking at the camera",
                "img_1": SHEET,
                "img_2": CLOSEUP,
                "img_3": {"path": os.path.join(BASE, "apt_living2bedroom_2.png"),
                          "description": "empty apartment living room with a sofa, morning light"},
                #"clips": 4,
                
            },
            "scene_03_livingroom": {
                "summary": "She lifts her shirt over her head, adjusting her shoulders, then her raised arms to get the garmet off, she throws it behind her on the ground. she has a white bra"
                            "in a soft British accent says 'I want you to' her tongue comes out of her mouth slightly and traces her top lip seductively moving from the right side to the left, then she continues speaking and says" 
                            "'fuck me right here on the couch', she is still centered in camera view half body shot, two arms come into frame from the edge of frame and grab her under her arms below her breasts, and she smiles and laughs as she lifts slightly into the air, scene ends there",
                "img_1": SHEET,
                "img_2": CLOSEUP,
                "img_3": {"path": os.path.join(BASE, "apt_living2bedroom_2.png"),
                                      "description": "empty apartment living room with a sofa, morning light"},
                #"clips": 4,
                
                "video": {"path": "scene_02_livingroom", "description": None},
                        },
            "scene_04_livingroom": {
                "summary": "Continuing from the playful lift — he lowers her back onto the sofa, her sheer bra barely containing her breasts, camera moves to view her from a high angle looking down at her POV, and she reaches up to pull him closer, whispering in a soft British accent 'don't keep me waiting'. His hands slide from under her arms down to her waist, she spreads her legs as she arches her back into the cushions, breathing heavier, eyes locked on the camera with a hungry smile. Scene ends with her pulling his face toward her chest.",
                "img_1": SHEET,
                "img_2": CLOSEUP,
                "img_3": {"path": os.path.join(BASE, "apt_living2bedroom_2.png"),
                          "description": "empty apartment living room with a sofa, morning light"},
                #"clips": 4,
                "video": {"path": "scene_03_livingroom", "description": None},
            },
            "scene_05_livingroom": {
                "summary": "Now fully reclined on the sofa, she unhooks her bra from the front and lets it fall, exposing her bare breasts to the camera, the move with soft body fluid dynamics recoiling from the motion, she then guides his head down to them while letting out a soft moan, his head between her breasts he moves his head side to side. In a breathy British accent she gasps 'yes, suck my titties, just like that', tangling her fingers in his hair as the camera slowly pushes in on her flushed face and heaving chest. Scene ends with her biting her lip and pulling him up for a kiss.",
                "img_1": SHEET_NSFW,
                "img_2": CLOSEUP,
                "img_3": {"path": os.path.join(BASE, "apt_living2bedroom_2.png"),
                          "description": "empty apartment living room with a sofa, morning light"},
                #"clips": 4,
                "video": {"path": "scene_04_livingroom", "description": None},
            },
        },
        comfy_client=comfy_client,
        output_dir=os.path.join(BASE, CHARACTER_FOLDER, "movie_output"),
        clips_per_scene=1,
        chain_scenes=False, #video chaining is handled manually in the scene configs above with the 'video' entry, so this is set to False
        clip_duration=10.0,
        turbo_lora=True,
        quant="int8",#int8 or bf16 only
    )

    director.run()
